apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: exam
  name: exam-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "deployments", "statefulsets"]
  verbs: ["get", "list", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exam-role-binding
  namespace: exam
subjects:
- kind: ServiceAccount
  name: default
  namespace: exam
roleRef:
  kind: Role
  name: exam-role
  apiGroup: rbac.authorization.k8s.io
